// src/templates/shared.ts - shared template helpers for project scaffolding

export interface GeneratedProject {
  files: Record<string, string>
}

/**
 * Generate a package.json string for a scaffolded project.
 */
export function generatePackageJson(
  name: string,
  deps: string[],
  framework: string,
): string {
  const dependencies: Record<string, string> = {}
  for (const dep of deps) {
    dependencies[dep] = 'latest'
  }

  const devDependencies: Record<string, string> = {
    typescript: '^5.0.0',
    '@types/node': '^20.0.0',
  }

  if (deps.includes('express')) {
    devDependencies['@types/express'] = '^5.0.0'
  }

  const scripts: Record<string, string> = {
    start: 'node dist/server.js',
    build: 'tsc',
    dev: 'npx tsx --watch server.ts',
  }

  const pkg = {
    name,
    version: '1.0.0',
    type: 'module',
    scripts,
    dependencies,
    devDependencies,
  }

  return JSON.stringify(pkg, null, 2) + '\n'
}

/**
 * Generate a .env.example file from a map of variable names to descriptions.
 */
export function generateEnvExample(envVars: Record<string, string>): string {
  const lines: string[] = []
  for (const [key, description] of Object.entries(envVars)) {
    lines.push(`# ${description}`)
    if (key === 'PORT') {
      lines.push(`${key}=3000`)
    } else if (key === 'FREE_TIER_REQUESTS') {
      lines.push(`${key}=10`)
    } else {
      lines.push(`${key}=`)
    }
    lines.push('')
  }
  return lines.join('\n')
}

/**
 * Generate a brief README for the scaffolded project.
 */
export function generateReadme(
  projectName: string,
  framework: string,
  backend: string,
): string {
  return `# ${projectName}

Generated by \`toll-booth init\`.

- **Framework:** ${framework}
- **Backend:** ${backend}

## Getting started

1. Copy \`.env.example\` to \`.env\` and fill in the values.
2. Install dependencies:

   \`\`\`bash
   npm install
   \`\`\`

3. Build and run:

   \`\`\`bash
   npm run build
   npm start
   \`\`\`

   Or run in development mode:

   \`\`\`bash
   npm run dev
   \`\`\`

## Powered by

[toll-booth](https://github.com/forgesworn/toll-booth) - L402 Lightning payment middleware.
`
}

/**
 * Generate a standard .gitignore for Node projects.
 */
export function generateGitignore(): string {
  return `node_modules/
dist/
.env
*.db
*.db-wal
*.db-shm
`
}

/**
 * Generate a standard tsconfig.json for ESM Node16 projects.
 */
export function generateTsConfig(): string {
  const config = {
    compilerOptions: {
      target: 'ES2022',
      module: 'Node16',
      moduleResolution: 'Node16',
      outDir: './dist',
      rootDir: '.',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      declaration: true,
    },
    include: ['server.ts'],
  }

  return JSON.stringify(config, null, 2) + '\n'
}
