// src/templates/shared.ts - shared template helpers for project scaffolding

export interface GeneratedProject {
  files: Record<string, string>
}

export const TOLL_BOOTH_DEPENDENCY_VERSION = '^6.0.0'
export const TOLL_BOOTH_DENO_PACKAGE = `npm:@forgesworn/toll-booth@${TOLL_BOOTH_DEPENDENCY_VERSION}`

export function tollBoothDenoSubpath(subpath: string): string {
  return `${TOLL_BOOTH_DENO_PACKAGE}/${subpath}`
}

const RUNTIME_DEPENDENCY_VERSIONS: Readonly<Record<string, string>> = Object.freeze({
  '@forgesworn/toll-booth': TOLL_BOOTH_DEPENDENCY_VERSION,
  express: '^5.2.1',
  hono: '^4.13.1',
  '@hono/node-server': '^2.1.0',
})

/**
 * Generate a package.json string for a scaffolded project.
 */
export function generatePackageJson(
  name: string,
  deps: string[],
  _framework: string,
): string {
  const dependencies: Record<string, string> = {}
  for (const dep of deps) {
    const version = RUNTIME_DEPENDENCY_VERSIONS[dep]
    if (!version) throw new Error(`No tested scaffold dependency range is configured for ${dep}`)
    dependencies[dep] = version
  }

  const devDependencies: Record<string, string> = {
    typescript: '^6.0.3',
    '@types/node': '^24.13.3',
  }

  if (deps.includes('express')) {
    devDependencies['@types/express'] = '^5.0.6'
  }
  if (_framework === 'bun') {
    devDependencies['@types/bun'] = '^1.3.14'
  }

  const scripts: Record<string, string> = {
    start: 'node dist/server.js',
    build: 'tsc',
    dev: 'npx tsx --watch server.ts',
  }

  const pkg = {
    name,
    version: '1.0.0',
    type: 'module',
    scripts,
    dependencies,
    devDependencies,
  }

  return JSON.stringify(pkg, null, 2) + '\n'
}

/**
 * Generate a .env.example file from a map of variable names to descriptions.
 */
export function generateEnvExample(envVars: Record<string, string>): string {
  const lines: string[] = []
  for (const [key, description] of Object.entries(envVars)) {
    lines.push(`# ${description}`)
    if (key === 'PORT') {
      lines.push(`${key}=3000`)
    } else if (key === 'FREE_TIER_REQUESTS') {
      lines.push(`${key}=10`)
    } else {
      lines.push(`${key}=`)
    }
    lines.push('')
  }
  return lines.join('\n')
}

/**
 * Generate a brief README for the scaffolded project.
 */
export function generateReadme(
  projectName: string,
  framework: string,
  backend: string,
): string {
  return `# ${projectName}

Generated by \`toll-booth init\`.

- **Framework:** ${framework}
- **Backend:** ${backend}

## Getting started

1. Copy \`.env.example\` to \`.env\` and fill in the values.
2. Install dependencies:

   \`\`\`bash
   npm install
   \`\`\`

3. Build and run:

   \`\`\`bash
   npm run build
   npm start
   \`\`\`

   Or run in development mode:

   \`\`\`bash
   npm run dev
   \`\`\`

## Powered by

[toll-booth](https://github.com/forgesworn/toll-booth) - L402 Lightning payment middleware.
`
}

/**
 * Generate a standard .gitignore for Node projects.
 */
export function generateGitignore(): string {
  return `node_modules/
dist/
.env
*.db
*.db-wal
*.db-shm
`
}

/**
 * Generate a standard tsconfig.json for ESM Node16 projects.
 */
export function generateTsConfig(framework: string = 'node'): string {
  const config = {
    compilerOptions: {
      target: 'ES2022',
      module: 'Node16',
      moduleResolution: 'Node16',
      outDir: './dist',
      rootDir: '.',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      declaration: true,
      types: framework === 'bun' ? ['node', 'bun'] : ['node'],
    },
    include: ['server.ts'],
  }

  return JSON.stringify(config, null, 2) + '\n'
}
